repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: yamlguard-k8s
        name: YAML Guard (K8s)
        entry: yamlguard --rules policies/k8s/core.yaml
        language: system
        files: '\.ya?ml$'
        pass_filenames: true

      - id: yamlguard-secrets
        name: YAML Guard (Secrets)
        entry: yamlguard --rules policies/security/secrets.yaml
        language: system
        files: '\.ya?ml$'
        exclude: '^policies/.*$'   # ← exclude policy files from secret scan
        pass_filenames: true
