version: "3.9"

services:
  api:
    build:
      context: .
      target: runtime
      args:
        VITE_API_BASE: "http://localhost:8000"  # baked into UI bundle
    ports:
      - "8000:8000"
    environment:
      # Allow browser callers from any localhost port (dev convenience)
      - YAML_GUARD_ALLOWED_ORIGINS=*
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys;urllib.request.urlopen('http://127.0.0.1:8000/health');sys.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  tests:
    build:
      context: .
      target: test
    depends_on:
      - api
    profiles: ["test"]
    # Example of running smoke tests instead of full pytest:
    # command: ["python", "scripts/smoke_validate.py", "--host", "http://api:8000"]

  # (Optional) A separate UI dev container if you want hot reload outside the image build
  ui-dev:
    image: node:22-alpine
    working_dir: /workspace/ui
    command: sh -c "npm install && VITE_API_BASE=http://localhost:8000 npm run dev"
    volumes:
      - ./ui:/workspace/ui
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    profiles: ["dev"]
