# Example CircleCI config
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build