apiVersion: v1
kind: Pod
metadata:
name: good-pod
spec:
containers:
- name: web
image: nginx:1.25@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
resources:
limits:
cpu: "100m"
memory: "128Mi"