name: API CI

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'pyproject.toml', 'policies/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**', 'pyproject.toml', 'policies/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run tests
      run: pytest -q
    
    - name: Test uvicorn startup
      run: |
        timeout 10s uvicorn yamlguard.server.main:app --host 127.0.0.1 --port 8000 || true
        echo "Uvicorn startup test completed"