name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-and-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install (editable with dev extras)
        run: |
          pip install -e .[dev]

      - name: Lint (ruff)
        run: |
            ruff check .

      - name: Tests (pytest)
        run: pytest -q

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: UI Install & Lint
        working-directory: ui
        run: |
          npm ci
          npm run lint

      - name: UI Build
        working-directory: ui
        run: npm run build

      - name: Upload UI Artifact
        if: matrix.python-version == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui/dist

